server:
  servlet:
    context-path: /pokedex/api/v1
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pokedex_db
    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true

pokemon-external-api: https://pokeapi.co/api/v2/pokemon